# For testing on local only, will need another docker-compose file for deploy
version: '3.6'
name: p-stack-fs
services:
  service:
    image: p-stack-fs
    container_name: p-stack-fs
    restart: always
    ports:
      - 3000:80
    env_file:
      - .env.docker
