version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  choose-workflow:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            db/(?!migrations).* run-db-pipeline true
            db/migrations/.* run-db-migrations true
            next-app/.* run-next-pipeline true
